# Generated by Django 2.2.1 on 2020-02-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passid', models.IntegerField()),
                ('survived', models.IntegerField()),
                ('pclass', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('age', models.FloatField()),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('ticket', models.CharField(max_length=250)),
                ('fare', models.FloatField()),
                ('embarked', models.CharField(max_length=250)),
            ],
        ),
    ]
